- .vscode/settings.json
- index.html
Feito com todos os membros do squad a estrutura HTML
> html structure

- index.html
- scripts/artes.js
- scripts/entretenimento.js
- scripts/esportes.js
Adicionando o Objeto com as questões.
> added-questions

- index.html
- style/style.css
- style/var.css
Css iniciado e paleta de cores definida
> css initialize

- index.html
- scripts/script.js
Foi iniciado o código do botão iniciar, que está funcionando parcialmente.
> início da criação da funcionalidade do botão iniciar.

- index.html
- scripts/script.js
if foi acrescentado, para que fosse possível selecionar o tema;
display none colocado para mostrar apenas as questões;
contador serve para fazer funcionar os selects.
> if acrescentado

- index.html
- scripts/script.js
- style/style.css
- style/var.css
ajustes e adições de códigos css
> Css update

- scripts/script.js
Dando funcionalidade no botão continuar e gerando a pagina de estatísticas.
> funcionalidade botao continuar

- scripts/script.js
Fiz o botão de reiniciar como solicitado.
> funcionalidade btn

- index.html
- scripts/script.js
- style/style-dark.css
Início da estilização do dark mode.
> Inicio da estilização dark mode.

- scripts/script.js
- style/style-dark.css
- style/style.css
Update no css para melhor visualização das perguntas, e cor do botão de continuar;
Update no script para arrumar erro ao reiniciar.
> updates no css e lógica do script

- index.html
- scripts/script.js
Adição da tag html de audio;
Adição do lógica para play e pause do audio quando clicado no botão;
Adição da lógica para alternância entre o botão de play para pause.
> adição do botão de audio

- index.html
- scripts/script.js
- style/style-dark.css
- style/style.css
Adição do botão de volta à página inicial na tabela;
Adição de indicação para áudio;
Ajuste nas lógicas.
> Ajuste btns

- index.html
- scripts/script.js
- style/style-dark.css
- style/style.css
* Funcionalidade para o timer;
* Troca de heigth e display;
* Função pause para o botão continuar;
> funcionalidade para o timer

- index.html
- scripts/script.js
- style/style.css
> bugs arrumados e alerta adicionado

- scripts/script.js
* Salvamento da hora, nome e tema em que o usuário terminou o Quiz.
* Ajeitando o cronometro.
> salvando alguns dados do usuario

- index.html
- scripts/script.js
- style/style-dark.css
- style/style.css
- style/var.css
Início da estilização da tela-ranking.
> Início da estilização da tela de ranking

- index.html
- scripts/script.js
- style/style.css
* Implementação da lógica da segunda tabela.
> logica população da segunda tabela

- scripts/script.js
> btnConcluir

- index.html
- scripts/pessoas.js
- scripts/script.js
* Lógica completa da primeira tabela;
* Implementação dos dados do usuário;
> primeiraTabela

- scripts/script.js
* Aplicando lógica e formando a data;
* Arrumando bug no contador de acertos;
* Arrumando formatação do tempo
> added date

- scripts/pessoas.js
- scripts/script.js
* Arrumando a formatação da data
* Colocando hora que foi feita o Quizz
> formatando data e colocando hora

- index.html
- style/style-dark.css
- style/style.css
- style/var.css
> updates no css

- style/style-dark.css
> ajuste no dark-mode

- scripts/script.js
> fixed bugs

- scripts/script.js
Reverts arthurrgsampaio/Projeto-Avaliativo-Quiz-JS#57
> Revert "fixed bugs"

- scripts/script.js
> pull da lógica das tabelas

- scripts/script.js
> arrumado o bug do horário
